### PR TITLE
Expense Categories

### PR DESCRIPTION
**Pull request by kcotugno**
Add a new Expense Category model to support the new Mavenlink feature.

@ahuth Please review.

### CODE REVIEW

**Comment by ahuth** [comment]
Should we add the expense category association to the expense model? We may not need it, but the API supports it.

**Comment by kcotugno** [comment]
Yep you're right.

**Comment by kcotugno** [comment]
Done!

**Comment by kcotugno** [comment]
@ahuth If you can merge this as I don't have permission, that would be great!

**Comment by ahuth** [comment]
Weird. Merging

**Pull request merged**
